version: '3'
services:
  app:
    container_name: gocorreios_server_app_test
    build:
      dockerfile: ./Dockerfile.test
      context: .
    restart: on-failure
    volumes:
      - .:/gocorreios_server_test
